apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: remnawave
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/esmaksimov/3x-ui-k8s
    path: remnawave
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: remnawave-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true