apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: "35.3.0"

    helm:
      values: |
        entryPoints:
          websecure:
            address: ":443/tcp"
          vpn:
            address: ":27282/tcp"
        ports:
          websecure:
            hostPort: 443
            protocol: TCP
            entryPoint: websecure
          vpn:
            port: 27282
            protocol: TCP
            entryPoint: vpn
        securityContext:
          capabilities:
            add:
              - NET_BIND_SERVICE
        rbac:
          enabled: true
        providers:
          kubernetesCRD:
            enabled: true
        ingressClass:
          enabled: true
          isDefaultClass: false
          name: traefik
        service:
          type: ClusterIP

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true