apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: "35.3.0"

    helm:
      values: |
        entryPoints:
          websecure:
            address: ":443/tcp"
          grpcreal:
            address: ":2083/tcp"
        ports:
          websecure:
            hostPort: 443
          grpcreal:
            port: 2083
            hostPort: 2083
          vlessgh:
            port: 36028
            hostPort: 36028
          trojangoogle:
            port: 49245
            hostPort: 49245
        securityContext:
          capabilities:
            add:
              - NET_BIND_SERVICE
        rbac:
          enabled: true
        providers:
          kubernetesCRD:
            enabled: true
        ingressClass:
          enabled: true
          isDefaultClass: false
          name: traefik
        service:
          type: ClusterIP

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true